apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: argo-workflows
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: argo-workflows
    version: 0.1.8
    description: The workflow engine for Kubernetes
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/92c5ed56-445e-44dd-bb9a-6cd8cfadbf36/argo-stacked-color-square.png?v=63798850762
    
