apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: chatwoot
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: chatwoot
    version: 0.1.5
    description: Open-source and self-hosted customer engagement suite.
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/1fa864cc-98b2-457d-afb8-ed0659a6caf4/chatwoot.png?v=63827245281
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
