apiVersion: v2
name: nvidia-operator
description: A helm chart for nvidia-operator
version: 0.1.4
appVersion: 0.1.15
dependencies:
- name: nvidia-operator
  version: 0.1.15
  repository: cm://app.plural.sh/cm/nvidia-operator
  condition: nvidia-operator.enabled
