apiVersion: plural.sh/v1alpha1
kind: Context
spec:
  bundles:
  - repository: grafana
    name: aws-grafana
  - repository: console
    name: console-aws
  - repository: kubeflow
    name: kubeflow-aws
  - repository: redis
    name: aws-redis
  - repository: bootstrap
    name: aws-k8s
  configuration:
    bootstrap:
      enableSnapshot: true
      ownerEmail: david@plural.sh
      txt_owner: david
      vpc_name: kubeflow-dev
    console:
      admin_email: david@plural.sh
      admin_name: david
      console_dns: console.kubeflow-aws.com
      git_email: vanderspek.david@gmail.com
      git_user: DavidSpek
    crossplane: {}
    grafana:
      hostname: grafana.kubeflow-aws.com
    grafana-tempo:
      tempoBucket: kubeflow-dev-tempo-tracing
    ingress-nginx: {}
    istio:
      kialiHostname: kiali.kubeflow-aws.com
    knative: {}
    kubeflow:
      hostname: kubeflow.kubeflow-aws.com
      pipelines_bucket: kubeflow-dev-pipelines-new
    monitoring: {}
    mysql:
      backup_bucket: kubeflow-dev-mysql-backups
      hostname: mysql-orchestrator.kubeflow-aws.com
    nvidia-operator: {}
    postgres:
      wal_bucket: kubeflow-dev-postgres-wal
    redis: {}
