apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: dex
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: dex
    version: 0.1.1
    description: federated identity provider for modern authentication
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/c356a1df-848e-4852-9893-3b3e9c36fd35/dex.jpeg?v=63791704095
    
