apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kserve
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: kserve
    version: 0.1.2
    description: kserve deployed on plural
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/2089f227-24a3-442d-a53b-941d12dd6d91/kserve.png?v=63817604294
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
