apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: kubeflow aws setup
  version: 0.1.4
spec:
  dependencies:
  - name: aws-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
  providers:
  - aws
  outputs:
    s3_access_key: s3_access_key
    s3_access_secret: s3_access_secret
