apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kubricks
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: kubricks
    version: 0.1.6
    description: kubricks deployed on plural
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/1fa91315-35a7-4d18-9e64-db5c95214195/kubricks.png?v=63822629638
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
