apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: lightdash
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: lightdash
    version: 0.1.3
    description: Lightdash instantly turns your dbt project into a full-stack BI platform.
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/432b8cac-a2f5-4440-8b29-d0610962ae06/lightdash.png?v=63826570237
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
