apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: hasura
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: hasura
    version: 0.1.8
    description: An open-source product that gives you GraphQL or REST APIs with built-in authorization on your data.
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/d714bcb7-82d2-496d-b70d-9f8ca73bb698/hasura.png?v=63830906377
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
