apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: argo-workflows aws setup 
  version: 0.1.5
spec:
  dependencies:
  - name: aws-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
  providers:
  - aws
