apiVersion: v2
name: mlflow
description: A helm chart for mlflow
version: 0.1.11
appVersion: 0.1.6
dependencies:
- name: mlflow
  version: 0.1.6
  repository: cm://app.plural.sh/cm/mlflow
- name: mlflow-standalone
  version: 0.1.5
  repository: cm://app.plural.sh/cm/mlflow
