apiVersion: v2
name: lightdash
description: A helm chart for lightdash
version: 0.1.0
appVersion: 0.1.3
dependencies:
- name: lightdash
  version: 0.1.3
  repository: cm://app.plural.sh/cm/lightdash
  condition: lightdash.enabled
