apiVersion: v2
name: lightdash
description: A helm chart for lightdash
version: 0.1.0
appVersion: 0.1.0
dependencies:
- name: lightdash
  version: 0.1.0
  repository: file:///home/david/Plural/plural-artifacts/lightdash/helm/lightdash
  condition: lightdash.enabled
