apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: spark
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: spark
    version: 0.1.0
    description: a unified analytics engine for large-scale data processing
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/c29e7964-1c53-477f-b071-2b397cf63815/spark.png?v=63803161811
    
