apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: ray
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: ray
    version: 0.1.5
    description: ray deployed on plural
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/32861411-b531-4d25-a9e4-1685d6ae7dc0/ray.png?v=63832368843
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
