apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: kyverno
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: kyverno
    version: 0.1.0
    description: Kubernetes Native Policy Management
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/cba9e42e-62d2-4715-bb15-de9e7d8c43cc/kyverno.png?v=63810424530
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
