apiVersion: v2
name: monitoring
description: A helm chart for monitoring
version: 0.1.7
appVersion: 0.2.2
dependencies:
- name: monitoring
  version: 0.2.2
  repository: cm://app.plural.sh/cm/monitoring
