apiVersion: v2
name: kubricks
description: A helm chart for kubricks
version: 0.1.0
appVersion: 0.1.3
dependencies:
- name: kubricks
  version: 0.1.3
  repository: cm://app.plural.sh/cm/kubricks
  condition: kubricks.enabled
