apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nocodb
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: nocodb
    version: 0.1.9
    description: An open-source alternative to Airtable that turns any database into a smart spreadsheet.
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/a052b432-212f-486e-90bb-6c0bc0f987e8/nocodb.png?v=63830908105
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
