apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: trino
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: trino
    version: 0.1.1
    description: A distributed SQL query engine for big data and analytics.
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/635d9ef5-5455-4657-9edd-190ea7ebd035/trino.png?v=63830908339
    

    {{- if .Values.global }}
    {{- if .Values.global.application }}
    {{- if .Values.global.application.links }}
    links:
    {{ toYaml .Values.global.application.links | nindent 6 }}
    {{- end }}
  {{- if .Values.global.application.info }}
  info:
  {{ toYaml .Values.global.application.info | nindent 4 }}
  {{- end }}
  {{- end }}
  {{- end }}
