apiVersion: v2
name: kubeflow
description: A helm chart for kubeflow
version: 0.1.0
appVersion: 0.1.6
dependencies:
- name: central-dashboard
  version: 0.1.6
  repository: cm://app.plural.sh/cm/kubeflow
- name: mysql-cluster
  version: 0.1.2
  repository: cm://app.plural.sh/cm/kubeflow
