apiVersion: v2
name: kubeflow
description: A helm chart for kubeflow
version: 0.1.38
appVersion: 0.1.28
dependencies:
- name: serving
  version: 0.1.28
  repository: cm://app.plural.sh/cm/kubeflow
  condition: serving.enabled
- name: tensorboards
  version: 0.1.11
  repository: cm://app.plural.sh/cm/kubeflow
  condition: tensorboards.enabled
- name: training-operator
  version: 0.1.3
  repository: cm://app.plural.sh/cm/kubeflow
  condition: training-operator.enabled
- name: volumes
  version: 0.1.10
  repository: cm://app.plural.sh/cm/kubeflow
  condition: volumes.enabled
- name: notebooks
  version: 0.1.24
  repository: cm://app.plural.sh/cm/kubeflow
  condition: notebooks.enabled
- name: mysql-cluster
  version: 0.1.14
  repository: cm://app.plural.sh/cm/kubeflow
  condition: mysql-cluster.enabled
- name: katib
  version: 0.1.20
  repository: cm://app.plural.sh/cm/kubeflow
  condition: katib.enabled
- name: pipelines
  version: 0.1.89
  repository: cm://app.plural.sh/cm/kubeflow
  condition: pipelines.enabled
- name: aws-iam-controller
  version: 0.0.7
  repository: cm://app.plural.sh/cm/kubeflow
  condition: aws-iam-controller.enabled
- name: profile-controller
  version: 0.1.44
  repository: cm://app.plural.sh/cm/kubeflow
  condition: profile-controller.enabled
- name: central-dashboard
  version: 0.1.35
  repository: cm://app.plural.sh/cm/kubeflow
  condition: central-dashboard.enabled
