apiVersion: v2
name: kubeflow
description: A helm chart for kubeflow
version: 0.1.29
appVersion: 0.1.17
dependencies:
- name: katib
  version: 0.1.17
  repository: cm://app.plural.sh/cm/kubeflow
- name: central-dashboard
  version: 0.1.25
  repository: cm://app.plural.sh/cm/kubeflow
- name: tensorboards
  version: 0.1.6
  repository: cm://app.plural.sh/cm/kubeflow
- name: volumes
  version: 0.1.5
  repository: cm://app.plural.sh/cm/kubeflow
- name: mysql-cluster
  version: 0.1.13
  repository: cm://app.plural.sh/cm/kubeflow
- name: notebooks
  version: 0.1.14
  repository: cm://app.plural.sh/cm/kubeflow
- name: mpi
  version: 0.1.7
  repository: cm://app.plural.sh/cm/kubeflow
- name: mxnet
  version: 0.1.5
  repository: cm://app.plural.sh/cm/kubeflow
- name: pytorch
  version: 0.1.5
  repository: cm://app.plural.sh/cm/kubeflow
- name: tensorflow
  version: 0.1.5
  repository: cm://app.plural.sh/cm/kubeflow
- name: xgboost
  version: 0.1.5
  repository: cm://app.plural.sh/cm/kubeflow
- name: pipelines
  version: 0.1.84
  repository: cm://app.plural.sh/cm/kubeflow
- name: profile-controller
  version: 0.1.35
  repository: cm://app.plural.sh/cm/kubeflow
- name: serving
  version: 0.1.21
  repository: cm://app.plural.sh/cm/kubeflow
