apiVersion: v2
name: crossplane
description: A helm chart for crossplane
version: 0.1.1
appVersion: 0.1.6
dependencies:
- name: crossplane
  version: 0.1.6
  repository: cm://app.plural.sh/cm/crossplane
