apiVersion: plural.sh/v1alpha1
kind: Dependencies
metadata:
  description: mlflow aws setup  
  version: 0.1.1
spec:
  breaking: true
  dependencies:
  - name: aws-bootstrap
    repo: bootstrap
    type: terraform
    version: '>= 0.1.1'
  providers:
  - aws
