apiVersion: v2
name: istio
description: A helm chart for istio
version: 0.1.5
appVersion: 0.1.99
dependencies:
- name: istio
  version: 0.1.99
  repository: cm://app.plural.sh/cm/istio
  condition: istio.enabled
