apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: oauth2-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: oauth2-proxy
    version: 0.1.8
    description: easy to use oauth solution for load balancers
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/099fa484-b9d1-458a-aeb9-f8009516ad8b/oauth-proxy.png?v=63792377885
    
