apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: nextcloud
spec:
  selector:
    matchLabels: {}
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: nextcloud
    version: 0.1.13
    description: the first completely integrated on-premises content collaboration platform
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/9dbccf2b-771a-4bfb-87b9-63646a253d1c/nextcloud-logo.png?v=63797452730
    
