apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: gitlab
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: gitlab
    version: 0.3.14
    description: unified dev ops experience based on git
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/0b78e1b6-ed5a-4e39-90a9-4beae4eb27c3/gitlab.png?v=63788748304
    
