apiVersion: v2
name: kserve
description: A helm chart for kserve
version: 0.1.0
appVersion: 0.1.2
dependencies:
- name: kserve
  version: 0.1.2
  repository: cm://app.plural.sh/cm/kserve
  condition: kserve.enabled
