apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: Helm
  componentKinds:
  - group: v1
    kind: Service
  - group: networking.k8s.io
    kind: Ingress
  - group: cert-manager.io
    kind: Certificate
  - group: apps
    kind: StatefulSet
  - group: apps
    kind: Deployment
  - group: batch
    kind: CronJob
  - group: batch
    kind: Job
  descriptor:
    type: monitoring
    version: 0.1.10
    description: deploy the open metrics suite to monitor your applications
    icons:
    - src: https://plural-assets.s3.us-east-2.amazonaws.com/uploads/repos/1ed5c2be-9d60-43db-b757-ee289e6524f6/[removal.ai]_tmp-60e4f98cbf90e.png?v=63792838055
    
